BotToken = "123456:AABBBCCCC"
AdminId = 11696011
Debug = false
TorrentDownloadPath = "/tmp"
ChatIdToKickUsersFrom = -21005536
BitBucketRepoUser = "yprez"
BitBucketRepo = "test"
BitBucketUser = ""
BitBucketPassword = ""
BitBucketTelegramChat = 11696011
